// <auto-generated />
namespace WijayanthaHardware.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class editedpowertoolmastertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editedpowertoolmastertable));
        
        string IMigrationMetadata.Id
        {
            get { return "201807211532494_edited powertool master table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
