// <auto-generated />
namespace WijayanthaHardware.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PowerToolMasterforce : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PowerToolMasterforce));
        
        string IMigrationMetadata.Id
        {
            get { return "201806201433298_PowerToolMaster-force"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
