// <auto-generated />
namespace WijayanthaHardware.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class category_lookup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(category_lookup));
        
        string IMigrationMetadata.Id
        {
            get { return "201806191445085_category_lookup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
